### ISSUE TITLE
[bug] "hide_disconnected_pins" ignores "loops" 

### ISSUE THREAD

**Issue by nataloko** [wireviz/WireViz#263]
When I enable the "hide_disconnected_pins" option on a connector with loops, I get a series of warnings (nod XX, port YY unrecognized) and the a wiring artefact on the drawing.

![XQI2fn2klt](https://user-images.githubusercontent.com/93059500/146811909-94fb4fc8-cd70-4ca6-ae1d-2b274fb93d11.png)

**Comment by kvid** [comment]
Thank you for reporting this bug. Please try my fix in PR #264 and make a review or comment about what you find. Does it resolve your issue fully?

**Comment by nataloko** [comment]
The fix works great thanks :)
