### ISSUE TITLE
Wire box removal.

### ISSUE THREAD

**Issue by jaggzh** [wireviz/WireViz#278]
Pardon the question: Can the actual box of connection information be hidden, so only the connectors and wires are visible, but not the box with labels?

**Comment by kvid** [comment]
Is this a duplication of #212 that also includes my [work-around suggestion](https://github.com/formatc1702/WireViz/issues/212#issuecomment-1030236831)? If that old issue also covers your use case completely, then I suggest you join that discussion and add comments with your use case and request(s).

**Comment by kvid** [comment]
@jaggzh - please reopen this issue and explain why if you don't agree that #212 covers your use case.
