### ISSUE TITLE
[feature] Hide Cable Blocks

### ISSUE THREAD

**Issue by heinduplessis** [wireviz/WireViz#326]
Sometimes I want to publish a simple wire diagram, but the intermediary "wire block" adds clutter and confusion to the general audience. Could someone add a "hidden_cable_block" property in the Yaml definition to indicate not to draw the intermediary cable block?

So for example ![demo01 1](https://github.com/wireviz/WireViz/assets/4996798/203dd812-2db7-4c77-bebd-96ab50b45680) would render with just the X1 and X2 blocks and NOT the W1 block. The white green and brown wires would connect directly to the two connectors (X1 and X2). The shield wire would obviously then be omitted in this example, but would show up again if the W1 hidden_cable_block is set to false or omitted again.

It would look something like this (ignore the line and the shield cable):
![fix](https://github.com/wireviz/WireViz/assets/4996798/6b5adce3-e541-4f92-bd3c-b78cee059abf)

**Comment by kvid** [comment]
This sems to be a duplicate of #212 - where a work-around is described. (#278 was another duplicate.)

**Comment by heinduplessis** [comment]
Thank you, I implemented the work-around.
