### ISSUE TITLE
Demo01.yml: syntax error in line 1 near 'connectors'

### ISSUE THREAD

**Issue by Basilisvirus** [wireviz/WireViz#334]
I installed wireviz following the instructions [here ](https://forum.graphviz.org/t/new-simplified-installation-procedure-on-windows/224) on windows 11.

More specifically, I downloaded [windows_10_cmake_Release_graphviz-install-10.0.1-win64.exe](https://gitlab.com/api/v4/projects/4207231/packages/generic/graphviz-releases/10.0.1/windows_10_cmake_Release_graphviz-install-10.0.1-win64.exe) from [here](https://gitlab.com/graphviz/graphviz/-/releases)

In github instructions it says in order to run wireviz, type wireviz:
![image](https://github.com/wireviz/WireViz/assets/18421898/10a576de-6530-4fde-9832-c6ac1f0cf941)

Now, when I try to run wireviz I get:

```
PS C:\Users\Vasilis> wireviz
wireviz : The term 'wireviz' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```

![image](https://github.com/wireviz/WireViz/assets/18421898/6c31614f-d153-4cf8-be49-4ff4ea91d2aa)

I can see it has graphviz in the environment variables:

![image](https://github.com/wireviz/WireViz/assets/18421898/cfc94431-6328-475f-8a8d-3cbbc4e5efc2)

But there is no "wireviz.exe" enywhere in my pc (At least I could not find it). I suspect windows instructions to run wireviz are not clear?

![image](https://github.com/wireviz/WireViz/assets/18421898/2458c42b-3a51-4888-8851-246a6a3fcf26)

I then found out that in[ WIndows, I need to run wireviz using dot.exe file](https://forum.graphviz.org/t/new-simplified-installation-procedure-on-windows/224/40?u=basilisvirus). This is not documented in the installation/run istructions.

My dot.exe version is:
```
PS C:\Users\Vasilis> dot -V
dot - graphviz version 10.0.1 (20240210.2158)
```
My python version:
```
PS C:\Users\Vasilis> python -V
Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.
```
OS is: windows 11 23H2

 But I get `syntax error in line 1 near 'connectors'` after downloading and running [demo01.yml](https://github.com/wireviz/WireViz/blob/master/examples/demo01.yml) using `dot.exe` command.

I downloaded demo01.yml and did not edit it before running it to make sure its the same file as in the git website.

Same thing happens if I -copy paste the same example- with notepad++ and using UTF-8 encoding:
![image](https://github.com/wireviz/WireViz/assets/18421898/cb994bdc-47dc-4f1c-bbf1-78684761cade)

I am using notepad++ to remove the BOM (in case the file has BOM) using the "Convert to UTF-8" and saving the file as UTF-8. 

Looking up the file as hex characters I cant tell exacly, but nothing looks off, the first hex are characters:

![image](https://github.com/wireviz/WireViz/assets/18421898/b518b376-18c0-4dfc-bc23-c8998a07e1c5)

How can I debug this issue further?

_Note that I use dot.exe to run wireviz, this is not mentioned in the documentation (at least I didnt find it). The documentation says that wireviz is run using the wireviz.exe_

I upload the source.yml file I try to use (same file as the demo01.yml example), insize a zip:
[source.zip](https://github.com/wireviz/WireViz/files/15127028/source.zip)

**Comment by kvid** [comment]
Can you please inform which version of WireViz you have installed, and how - e.g. `pip3 install wireviz` as describe in the [README](https://github.com/wireviz/WireViz/blob/master/docs/README.md). In [CONTRIBUTING](https://github.com/wireviz/WireViz/blob/master/docs/CONTRIBUTING.md), it's also described the other information you're expected to include when submitting a new issue.

When installed correctly, it should be possible to execute WireViz from the command prompt by using the command `wireviz` to execute python with the correct `.py` file behind the scene. Normally, you're not supposed to execute the `dot` command directly, but if you do, you cannot give it a `.yml` file containing WireViz syntax as input argument. WireViz should read the `.yml` file, output some other files, and execute the `dot` tool as part of the internal process.

**Comment by Basilisvirus** [comment]
All right, I figured it out. 
On windows:
1. Install python from their website.
2. If not installed with python, install pip.
3. Follow the github's instructions on installing wireviz (aka pip3 install wireviz)

The issue is then resolved. It seems like the instructions I followed was to install graphviz, not wireviz.
