### ISSUE TITLE
length precision

### ISSUE THREAD

**Issue by freiadam** [wireviz/WireViz#340]
If "length: 1000 mm" in YAML  the result will be 1000.0 mm in the output files. I think it should be 1000 mm. Is there a solution for this?

**Comment by kvid** [comment]
The relevant fixes are now merged into the `release/v0.4.1-rc` branch of PR #365 that is not yet released, but also describes how you can install the latest collection of fixes before the release.

**Comment by kvid** [comment]
Closed after releasing v0.4.1.
