### ISSUE TITLE
[bug] Pip package is missing templates dir and files in v0.4

### ISSUE THREAD

**Issue by drid** [wireviz/WireViz#345]
It seems that the templates dir is not packaged by CI
```
FileNotFoundError: [Errno 2] No such file or directory: '/home/user/.local/pipx/venvs/wireviz/lib/python3.11/site-packages/wireviz/templates/simple.html'

```

**Comment by kvid** [comment]
@drid - thank's for reporting this error, but please provide information about your set of versions as described in [CONTRIBUTING.md](https://github.com/wireviz/WireViz/blob/master/docs/CONTRIBUTING.md) and how you installed WireViz and dependencies. Otherwise, it might be hard to help you when nobody knows how to recreate the error you report.

**Comment by JohannesSteiner** [comment]
@kvid I got the same issue today after updating to wire-viz 0.4. Uninstalling and re-installing did not resolve the issue.

Looks like the [template folder from src/wireviz/templates](https://github.com/wireviz/WireViz/tree/master/src/wireviz/templates) is missing in the installed package (refer to picture below).
![Bildschirmfoto vom 2024-05-17 01-24-14](https://github.com/wireviz/WireViz/assets/22997148/f7627489-c2ef-45b1-bdcc-e54d8389d773)

System information:
* WireViz 0.4 (in venv)
* Python 3.11.6 
* Ubuntu 23.10

**Comment by kvid** [comment]
Check out PR #347 that might resolve this issue. Please comment the outcome of your testing.

**Comment by formatc1702** [comment]
I hope #347 fixed this. Please feel free to reopen issue if not.

**Comment by ScottH-ideasatsea** [comment]
just installed on windows using pip3

Errors with

FileNotFoundError: [Errno 2] No such file or directory: AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\wireviz\\templates\\simple.html'

wireviz --version

WireViz 0.4
