### ISSUE TITLE
[bug] templates missing when installed using pip3

### ISSUE THREAD

**Issue by AlexHaijiaZhu** [wireviz/WireViz#362]
WireViz (0.4), Graphviz (11.0.0), Python (3.12)， Windows 11 

When install the WireViz using `pip3 install wireviz`, it seems that the template folder are not installed which lead to the error message:
`FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Python312\\Lib\\site-packages\\wireviz\\templates\\simple.html'`

To fix it: copy the template folder to the `C:\\PythonXXX\\Lib\\site-packages\\wireviz\\`

**Comment by kvid** [comment]
This is a duplication of #345. Please join the discussion there, and close this one.
