### ISSUE TITLE
(need help) Connector with different crimps

### ISSUE THREAD

**Issue by ElPi23** [wireviz/WireViz#372]
good day,
im using the version 0.4 and i have created a library with all the connectors and the corresponding pins in it. 
My question/problem now is, how can I create a connector that uses two different crimp types (the first 6 pins have a different crimp than the other 29)?
Is that even possible?

**Comment by kvid** [comment]
Please provide an example YAML input with such a connector and describe the difference between the result you get and what you want.

**Comment by martinrieder** [comment]
There is the possibility to list crimps as additional components with `qty_multiplier: populated`, but that would not allow different pins to have their crimps counted separately. You would have to define a fixed quantity and possibly use pin coloring to mark which crimps would fit.

Check #300 for details.

**Comment by martinrieder** [comment]
@ElPi23 You could also split up your connector into two separate ones. They can be aligned in the layout similar to #325

**Comment by ElPi23** [comment]
thanks for your help. 

I will close this
