### ISSUE TITLE
Query: Grouping different connectors for the same component

### ISSUE THREAD

**Issue by akikinho** [wireviz/WireViz#385]
Hello Wireviz Team,
I have a question. I have a component for which there are 4 different connectors. I want to have a feature to group all these connectors for the same component. Is it possible? Right now, I am able to make all the connections, but it is scattered and the component is not visible anymore.

Thank you!

**Comment by kvid** [comment]
Hi. Your question seems to be a duplicate of https://github.com/wireviz/WireViz/blob/master/docs/CHANGELOG.md
