### ISSUE TITLE
OSError: No file or directory found at spiral_keras_model.h5

### ISSUE THREAD

**Issue by project-set** [wireviz/WireViz#394]
hello, please help me..thanks

---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
Cell In[16], line 1
----> 1 model = load_model('spiral_keras_model.h5')
      2 class_names = ['1 Healthy-Spiral', '0 Parkinsons-Spiral']

File ~\anaconda3\Lib\site-packages\keras\src\saving\saving_api.py:262, in load_model(filepath, custom_objects, compile, safe_mode, **kwargs)
    254     return saving_lib.load_model(
    255         filepath,
    256         custom_objects=custom_objects,
    257         compile=compile,
    258         safe_mode=safe_mode,
    259     )
    261 # Legacy case.
--> 262 return legacy_sm_saving_lib.load_model(
    263     filepath, custom_objects=custom_objects, compile=compile, **kwargs
    264 )

File ~\anaconda3\Lib\site-packages\keras\src\utils\traceback_utils.py:70, in filter_traceback.<locals>.error_handler(*args, **kwargs)
     67     filtered_tb = _process_traceback_frames(e.__traceback__)
     68     # To get the full stack trace, call:
     69     # `tf.debugging.disable_traceback_filtering()`
---> 70     raise e.with_traceback(filtered_tb) from None
     71 finally:
     72     del filtered_tb

File ~\anaconda3\Lib\site-packages\keras\src\saving\legacy\save.py:234, in load_model(filepath, custom_objects, compile, options)
    232 if isinstance(filepath_str, str):
    233     if not tf.io.gfile.exists(filepath_str):
--> 234         raise IOError(
    235             f"No file or directory found at {filepath_str}"
    236         )
    238     if tf.io.gfile.isdir(filepath_str):
    239         return saved_model_load.load(
    240             filepath_str, compile, options
    241         )

OSError: No file or directory found at spiral_keras_model.h5

**Comment by kvid** [comment]
@project-set - thank's for reporting this error, but please provide information about your set of versions as described in [CONTRIBUTING.md](https://github.com/wireviz/WireViz/blob/master/docs/CONTRIBUTING.md) and how you installed WireViz and dependencies. Otherwise, it might be hard to help you when nobody knows how to recreate the error you report.
