### ISSUE TITLE
[query] CHASSIS GROUND (MAIN)

### ISSUE THREAD

**Issue by akikinho** [wireviz/WireViz#397]
Hello,
Is there a way to show the chassis ground (main) in Wireviz ? Can it be shown using splice?

Thank you and Best Regards,

**Comment by kvid** [comment]
> Try creating a connector with `style: simple` and `type: GROUND` attributes.

That will work, and a "Connector, GROUND" entry will be added to the BOM unless you also add connector attribute `ignore_in_bom: true`.

> It is a bit counter-intuitive that type describes the label that is displayed. Effectively, this kind of connector is also what can be used as a splice.

The `type` describes the type of connector (not label) and is also used in the BOM entry. The name of a `simple` connector is hidden by default unless you also add connector attribute `show_name: true`.

It's also possible not providing a `type`, but with an empty `type`, the connector node becomes very tiny unless also adding the name or e.g. an image like this:
![chassis-ground-smaller drawio](https://github.com/wireviz/WireViz/assets/12657033/92113203-ba04-4631-b6ae-5f50ef5318bf)

**Comment by kvid** [comment]
Chassis ground is not necessarily the same as earth ground, and I didn't find the chassis ground symbol as a unicode character.

**Comment by akikinho** [comment]
Thank you @kvid @martinrieder !
